import java.util.Scanner;
public class Main {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        String BillTo_Name, BillTo_No,Address, BillTo_Transaction, BillTo_Contact, BillTo_Email;
        System.out.print("Enter Bill To Name: ");
        BillTo_Name = input.nextLine();
        System.out.print("Enter Bill To No: ");
        BillTo_No = input.nextLine();
        System.out.print("Enter Bill To Address: ");
        Address = input.nextLine();
        System.out.print("Enter Bill To Contact: ");
        BillTo_Contact = input.nextLine();
        System.out.print("Enter Bill To Email: ");
        BillTo_Email = input.nextLine();
        System.out.print("Enter Bill To Transaction Number: ");
        BillTo_Transaction = input.nextLine();

        Scanner Sn = new Scanner(System.in);
        String ShipTo_Name, ShipTo_No,ShipTo_Address, ShipTo_Transaction, ShipTo_Contact, ShipTo_Email;
        System.out.println("Enter Ship To Name: ");
        ShipTo_Name = input.nextLine();
        System.out.println("Enter Ship To No: ");
        ShipTo_No = input.nextLine();
        System.out.println("Enter Ship To Address: ");
        ShipTo_Address = input.nextLine();
        System.out.println("Enter Ship To Contact: ");
        ShipTo_Contact = input.nextLine();
        System.out.println("Enter Ship To Email: ");
        ShipTo_Email = input.nextLine();
        System.out.println("Enter Ship To Transaction Number: ");
        ShipTo_Transaction = input.nextLine();

        Scanner Input = new Scanner(System.in);
        int s_no, Code ,HSN_Code, Quantity;
        double Rate,Amount;
        String Name, Units, Tax;
        System.out.print("Enter Product1 Name : ");
        Name = Input.nextLine();
        System.out.print("Enter Product1 Unit : ");
        Units = Input.nextLine();
        System.out.print("Enter Product1 Tax : ");
        Tax = Input.nextLine();
        System.out.println("Enter Product1 s.No : ");
        s_no = Input.nextInt();
        System.out.println("Enter Product1 Code : ");
        Code = Input.nextInt();
        System.out.print("Enter Product1 Quantity : ");
        Quantity = Input.nextInt();
        System.out.print("Enter Product1 Rate : ");
        Rate = Input.nextInt();
        System.out.print("Enter Product1 Amount : ");
        Amount = Input.nextInt();
        System.out.print("Enter Product1 HSnCode : ");
        HSN_Code = Input.nextInt();

        Scanner S = new Scanner(System.in);
        int sno, code , HSNCode, quantity;
        double rate, amount;
        String name, units, tax;
        System.out.print("Enter Product2 Name : ");
        name = S.nextLine();
        System.out.print("Enter Product2 Unit : ");
        units = S.nextLine();
        System.out.print("Enter Product2 Tax : ");
        tax = S.nextLine();
        System.out.print("Enter Product2 SNo : ");
        sno = S.nextInt();
        System.out.print("Enter Product2 Code : ");
        code = S.nextInt();
        System.out.print("Enter Product2 Quantity : ");
        quantity = S.nextInt();
        System.out.print("Enter Product2 Rate : ");
        rate = S.nextInt();
        System.out.print("Enter Product2 Amount : ");
        amount = S.nextInt();
        System.out.print("Enter Product2 HSNCode : ");
        HSNCode =  S.nextInt();

        Scanner S1 = new Scanner(System.in);
        int SNo, PCode, HNScode, PQuantity;
        double PRate, PAmount;
        String PName, PUnits, PTax;
        System.out.print("Enter Product3 Name : ");
        PName = S1.nextLine();
        System.out.print("Enter Product3 Unit : ");
        PUnits = S1.nextLine();
        System.out.print("Enter Product3 Tax : ");
        PTax = S1.nextLine();
        System.out.print("Enter Product3 S.No : ");
        SNo = S1.nextInt();
        System.out.print("Enter Product3 PCode : ");
        PCode = S1.nextInt();
        System.out.print("Enter Product3 Quantity : ");
        PQuantity = S1.nextInt();
        System.out.print("Enter Product3 Rate : ");
        PRate = S1.nextInt();
        System.out.print("Enter Product3 Amount : ");
        PAmount = S1.nextInt();
        System.out.print("Enter Product3 HNSCode : ");
        HNScode = S1.nextInt();

        Scanner S2 = new Scanner(System.in);
        int S_No, P_Code,HNS_code,  P_Quantity;
        double P_Rate, P_Amount;
        String P_Name, P_Units, P_Tax;
        System.out.print("Enter Product4 Name : ");
        P_Name = S2.nextLine();
        System.out.print("Enter Product4 Unit : ");
        P_Units = S2.nextLine();
        System.out.print("Enter Product4 Tax : ");
        P_Tax = S2.nextLine();
        System.out.print("Enter Product4 S.No : ");
        S_No = S2.nextInt();
        System.out.print("Enter Product4 PCode : ");
        P_Code = S2.nextInt();
        System.out.print("Enter Product4 Quantity : ");
        P_Quantity = S2.nextInt();
        System.out.print("Enter Product4 Rate : ");
        P_Rate = S2.nextInt();
        System.out.print("Enter Product4 Amount : ");
        P_Amount = S2.nextInt();
        System.out.print("Enter Product4 HNSCode : ");
        HNS_code = S2.nextInt();


        Scanner S3 = new Scanner(System.in);
        int S_no, P_code, P_quantity, P_rate;
        double P_amount,P_HSNcode;
        String P_name, P_units, P_tax;
        System.out.print("Enter Product5 Name : ");
        P_name = S3.nextLine();
        System.out.print("Enter Product5 Unit : ");
        P_units = S3.nextLine();
        System.out.print("Enter Product5 Tax : ");
        P_tax = S3.nextLine();
        System.out.print("Enter Product5 S.No : ");
        S_no = S3.nextInt();
        System.out.print("Enter Product5 PCode : ");
        P_code = S3.nextInt();
        System.out.print("Enter Product5 Quantity : ");
        P_quantity = S3.nextInt();
        System.out.print("Enter Product5 Rate : ");
        P_rate = S3.nextInt();
        System.out.print("Enter Product5 Amount : ");
        P_amount = S3.nextInt();
        System.out.print("Enter Product5 HSNCode : ");
        P_HSNcode = S3.nextInt();


        Scanner S4 = new Scanner(System.in);
        int Sno, Pcode, Pquantity, Prate;
        double Pamount,PHSNcode;
        String Pname, Punits, Ptax;
        System.out.print("Enter Product6 Name : ");
        Pname = S4.nextLine();
        System.out.print("Enter Product6 Unit : ");
        Punits = S4.nextLine();
        System.out.print("Enter Product6 Tax : ");
        Ptax = S4.nextLine();
        System.out.print("Enter Product6 S.No : ");
        Sno = S4.nextInt();
        System.out.print("Enter Product6 PCode : ");
        Pcode = S4.nextInt();
        System.out.print("Enter Product6 Quantity : ");
        Pquantity = S4.nextInt();
        System.out.print("Enter Product6 Rate : ");
        Prate = S4.nextInt();
        System.out.print("Enter Product6 Amount : ");
        Pamount = S4.nextInt();
        System.out.print("Enter Product6 HSNCode : ");
        PHSNcode = S4.nextInt();


        Scanner S5 = new Scanner(System.in);
        int SerialNo, ProductCode, ProductQuantity, ProductRate, ProductAmount,PHSN_code;
        String ProductName, ProductUnits, ProductTax;
        System.out.print("Enter Product7 Name : ");
        ProductName = S5.nextLine();
        System.out.print("Enter Product7 Unit : ");
        ProductUnits = S5.nextLine();
        System.out.print("Enter Product7 Tax : ");
        ProductTax = S5.nextLine();
        System.out.print("Enter Product7 S.No : ");
        SerialNo = S5.nextInt();
        System.out.print("Enter Product7 PCode : ");
        ProductCode = S5.nextInt();
        System.out.print("Enter Product7 Quantity : ");
        ProductQuantity = S5.nextInt();
        System.out.print("Enter Product7 Rate : ");
        ProductRate = S5.nextInt();
        System.out.print("Enter Product7 Amount : ");
        ProductAmount = S5.nextInt();
        System.out.print("Enter Product7 HSNCode : ");
        PHSN_code = S5.nextInt();

        double Total =(Amount+amount+P_Amount+P_amount+amount+PAmount+ProductAmount);
        double Discount =(Total*0.6368);
        double Grand_Total =(Total-Discount);

       System.out.println("\tBill To:\t\t\t\t\t\t\t\t\t\t\t\tShip to:\t\t\t\t\t");
       System.out.println("\t"+BillTo_Name+"\t\t\t\t\t\t\t\t\t"+ShipTo_Name+"\t\t\t\t\t");
       System.out.println("\t"+BillTo_No+".\t\t\t\t\t\t\t\t\t"+ShipTo_No+"\t\t\t\t\t");
       System.out.println("\t"+Address+"\t\t\t\t\t\t"+ShipTo_Address+"\t\t\t\t\t");
       System.out.println("\t"+BillTo_Transaction+"\t\t\t\t\t\t\t\t\t\t"+ShipTo_Transaction+"\t\t\t\t\t");
       System.out.println("\t"+BillTo_Contact+"\t\t\t\t\t\t\t\t\t"+ShipTo_Contact+"\t\t\t\t\t");
       System.out.println("\t"+BillTo_Email+"\t\t\t\t\t\t"+ShipTo_Email+"\t\t\t\t\t");
       System.out.println("-----------------------------------------------------------------------------------------------");
       System.out.println("\t\t\t\bPayment Date:"+"7 days from date of delivery\t\t\t\bPayment Terms:"+"100% against invoice");
       System.out.println("-----------------------------------------------------------------------------------------------");
       System.out.println("S.No|Product Code| \tProduct Name \t|\tHSN Code| \tQuality | Units |\tRate |\tTax|\t Amount ");
       System.out.println("-----------------------------------------------------------------------------------------------");
       System.out.println(" "+s_no+"\t|\t"+Code+"  \t | "+Name+"\t| "+HSN_Code+"\t|\t "+Quantity+" \t|"+"\t"+Units+" | "+Rate+"  |\t"+Tax+" |\t"+ Amount);
       System.out.println("-----------------------------------------------------------------------------------------------");
       System.out.println(" "+sno+"\t|\t"+code+" \t | "+name+"\t\t\t| "+HSNCode+"\t|\t "+quantity+" \t|\t"+units+" | "+rate+" \t| "+tax+"\t|\t"+amount);
       System.out.println("-----------------------------------------------------------------------------------------------");
       System.out.println(" "+SNo+"\t|\t"+PCode+" \t| "+PName+" | "+HNScode+"\t|\t "+PQuantity+" \t|\t"+PUnits+" | "+PRate+" \t| "+PTax+"\t|\t"+PAmount);
       System.out.println("-----------------------------------------------------------------------------------------------");
       System.out.println(" "+S_No+"\t|\t"+P_Code+" \t| "+P_Name+"\t| "+HNS_code+"\t|\t "+P_Quantity+" \t|\t"+P_Units+" | "+P_Rate+" \t| "+P_Tax+"\t|\t"+P_Amount);
       System.out.println("-----------------------------------------------------------------------------------------------");
       System.out.println(" "+S_no+"\t|\t"+P_code+" \t| "+P_name+"\t| "+P_HSNcode+"\t|\t "+P_quantity+" \t|\t"+P_units+" | "+P_rate+" \t| "+P_tax+"\t|\t"+P_amount);
       System.out.println("-----------------------------------------------------------------------------------------------");
       System.out.println(" "+Sno+"\t|\t"+Pcode+" \t| "+Pname+"\t\t| "+PHSNcode+"\t|\t "+Pquantity+" \t|\t"+Punits+" | "+Prate+" \t| "+Ptax+"\t|\t"+Pamount);
       System.out.println("-----------------------------------------------------------------------------------------------");
       System.out.println(" "+SerialNo+"\t|\t"+ProductCode+" \t| "+ProductName+"\t| "+PHSN_code+"\t|\t "+ProductQuantity+" \t|\t"+ProductUnits+" | "+ProductRate+" \t| "+ProductTax+"\t|\t"+ProductAmount);
        System.out.println("-----------------------------------------------------------------------------------------------");
        System.out.println("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tTotal\t\t|\t"+Total);
        System.out.println("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t-------------");
        System.out.println("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tDiscounts\t|\t\t"+Discount+"\t\t");
        System.out.println("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t-------------");
        System.out.println("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGrand total\t|\t"+Grand_Total+"\t\t\t");
        System.out.println("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t------------------------");
    }

}
